name: .NET Core Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      if: github.ref == 'refs/heads/main'
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Install dependencies
      run: dotnet restore PullRequestQuantifier.sln
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Build
      run: dotnet build PullRequestQuantifier.sln --configuration Release --no-restore
    
    - name: Restore Windows Projects
      if: github.ref == 'refs/heads/main'
      run: msbuild PullRequestQuantifierDotNetFull.sln /t:Restore /p:Configuration=Release 
    - name: Build Windows Projects
      if: github.ref == 'refs/heads/main'
      run: msbuild PullRequestQuantifierDotNetFull.sln /p:Configuration=Release

    - name: Test
      run: dotnet test PullRequestQuantifier.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings.xml -r ./coverlet-results
    - name: Install and run report generator tool
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator.exe -reports:coverlet-results/**/*.xml -targetdir:./coverage-report -reporttypes:Html
    - name: Upload code coverage results
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report/*

    - name: Pack
      if: github.ref == 'refs/heads/main'
      run: dotnet pack PullRequestQuantifier.sln --configuration Release  /p:PublicRelease=true
    - name: Push package to NuGet
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push src\Clients\PullRequestQuantifier.Client\bin\Release\PullRequestQuantifier.*.nupkg --api-key ${{ secrets.nugetKey }} --source https://api.nuget.org/v3/index.json

    - name: Publish local context generator
      #if: github.ref == 'refs/heads/main'
      run: dotnet publish -c Release -r win-x64 --output ./release/PullRequestQuantifier.Local.Context ./src/Clients/PullRequestQuantifier.Local.Context/PullRequestQuantifier.Local.Context.csproj --self-contained=false /p:PublishSingleFile=true
    - name: Publish local client
      #if: github.ref == 'refs/heads/main'
      run: dotnet publish -c Release -r win-x64 --output ./release/PullRequestQuantifier.Local.Client ./src/Clients/PullRequestQuantifier.Local.Client/PullRequestQuantifier.Local.Client.csproj --self-contained=false /p:PublishSingleFile=true
    
    - name: Upload release artifacts
      #if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/
    - name: Display structure of downloaded files  1
      run: ls -R
      working-directory: ./

    - name: Create a Release
      #if: github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - uses: actions/download-artifact@v2
      with:
        name: release
        path: ./
    - name: Display structure of downloaded files 2
      run: ls -R
      working-directory: ./

    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./a/PullRequestQuantifier/PullRequestQuantifier/release
        asset_name: release.zip
        asset_content_type: application/zip